[build]
  publish = "public"
  #command = "git submodule update --init --recursive && hugo"
  command = "hugo"

[context.production.environment]
  #HUGO_VERSION = "0.44"
  HUGO_VERSION = "0.162.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
